import os
import sys
import shutil
import subprocess
from pathlib import Path

def setup_comfyui():
    """Set up ComfyUI and its dependencies"""
    # Clone ComfyUI
    if not Path("ComfyUI").exists():
        subprocess.run([
            "git", "clone", "--depth", "1",
            "https://github.com/comfyanonymous/ComfyUI.git"
        ], check=True)
    
    # Install ComfyUI requirements
    subprocess.run([
        "pip", "install", "-r", "ComfyUI/requirements.txt"
    ], check=True)
    
    # Clone PuLID Flux custom node
    custom_nodes = Path("ComfyUI/custom_nodes")
    custom_nodes.mkdir(exist_ok=True)
    
    pulid_flux = custom_nodes / "ComfyUI_PuLID_Flux_ll"
    if not pulid_flux.exists():
        subprocess.run([
            "git", "clone", "--depth", "1",
            "https://github.com/lldacing/ComfyUI_PuLID_Flux_ll.git",
            str(pulid_flux)
        ], check=True)
    
    # Create dummy antelopev2.zip
    antelope = Path("ComfyUI/models/insightface/models/antelopev2.zip")
    if not antelope.exists():
        antelope.parent.mkdir(parents=True, exist_ok=True)
        with open(antelope, "w") as f:
            pass
    
    # Create dummy custom_node folder
    dummy_node = Path("ComfyUI/custom_nodes/ComfyUI")
    if dummy_node.exists():
        init_file = dummy_node / "__init__.py"
        if not init_file.exists():
            with open(init_file, "w") as f:
                f.write("# Autogenerated stub to satisfy ComfyUI importer\n")
    
    print("✅ ComfyUI setup complete")

if __name__ == "__main__":
    setup_comfyui() 